import { Food } from "../models/food";

export const foods: Food[] = [
    {
      id: '1',
      name: 'Margherita Pizza',
      thumbnailUrl: 'assets/hero_slide1.jpg',
      imageUrls: ['https://example.com/pizza1.jpg', 'https://example.com/pizza2.jpg'],
      description: 'Classic pizza with fresh tomatoes, mozzarella, and basil.',
      rating: 4.7,
      category: 'Pizza',
      servingSize: '1 slice',
      price: 8.99,
      calories: 250,
      protein: 12,
      carbohydrates: 30,
      fats: 10
    },
    {
      id: '2',
      name: 'Cheeseburger',
      thumbnailUrl: 'assets/hero_slide2.jpg',
      imageUrls: ['https://example.com/burger1.jpg'],
      description: 'Juicy beef patty with cheddar cheese, lettuce, tomato, and special sauce.',
      rating: 4.5,
      category: 'Burger',
      servingSize: '1 burger',
      price: 7.49,
      calories: 550,
      protein: 28,
      carbohydrates: 45,
      fats: 30
    },
    {
      id: '3',
      name: 'Caesar Salad',
      thumbnailUrl: 'assets/hero_slide3.png',
      imageUrls: ['https://example.com/salad1.jpg'],
      description: 'Fresh romaine lettuce, croutons, parmesan cheese, and Caesar dressing.',
      rating: 4.2,
      category: 'Salad',
      servingSize: '1 bowl',
      price: 6.5,
      calories: 180,
      protein: 7,
      carbohydrates: 12,
      fats: 12
    },
    {
      id: '4',
      name: 'Spaghetti Carbonara',
      thumbnailUrl: 'assets/hero_slide5.jpg',
      imageUrls: ['https://example.com/spaghetti1.jpg'],
      description: 'Pasta with creamy sauce, pancetta, and parmesan cheese.',
      rating: 4.6,
      category: 'Pasta',
      servingSize: '1 plate',
      price: 9.99,
      calories: 450,
      protein: 18,
      carbohydrates: 60,
      fats: 20
    },
    {
      id: '5',
      name: 'Chocolate Cake',
      thumbnailUrl: 'assets/hero_slide1.jpg',
      imageUrls: ['https://example.com/cake1.jpg'],
      description: 'Rich and moist chocolate cake topped with chocolate ganache.',
      rating: 4.8,
      category: 'Dessert',
      servingSize: '1 slice',
      price: 4.99,
      calories: 400,
      protein: 5,
      carbohydrates: 50,
      fats: 20
    },
];